export const LOADING = 'loading'
export const ERROR ='error'
export const GETSUDENTS="getAllStudnets"
export const GETASSIGNMENTS = 'getassignments'
export const GETALLREQUESTS="getallrequest"
export const ADDNEWREQUEST="addnewrequest"
export const UPDATETHEREOPENREQUEST="updateReopenRequest"
export const UPDATEAFETERFEEPAYMENT="updateAfterfeepayment"
export const GETATTENDENCE = 'getattendence'
export const GET = 'getattendence'